test: add more tricky diff tests

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -27,36 +27,34 @@ if test -z "$noxx" && grep -Hni xx""x $allfiles; then
 fi
 
 if test -z "$gofiles"; then
-  # No go file, no more checks to do.
-  exit
-fi
+  # Go specific tests in this branch.
+  echo -n 'formatting...'
+  gofmt -l $gofiles >"$tmpfile" 2>&1
+  echo -en "\r\e[K"
+  if test -s "$tmpfile"; then
+    echo "Error: gofmt failed for these files:"
+    cat "$tmpfile"
+    exit 1
+  fi
 
-echo -n 'formatting...'
-gofmt -l $gofiles >"$tmpfile" 2>&1
-echo -en "\r\e[K"
-if test -s "$tmpfile"; then
-  echo "Error: gofmt failed for these files:"
-  cat "$tmpfile"
-  exit 1
-fi
+  echo -n 'linting...'
+  revive ./... >"$tmpfile" 2>&1
+  echo -en "\r\e[K"
+  if test -s "$tmpfile"; then
+    echo "Error: revive failed:"
+    cat "$tmpfile"
+    exit 1
+  fi
 
-echo -n 'linting...'
-revive ./... >"$tmpfile" 2>&1
-echo -en "\r\e[K"
-if test -s "$tmpfile"; then
-  echo "Error: revive failed:"
-  cat "$tmpfile"
-  exit 1
-fi
-
-echo -n 'testing...'
-go test ./... >"$tmpfile" 2>&1
-result="$?"
-echo -en "\r\e[K"
-if test "$result" -ne 0; then
-  echo 'Error: tests failed, go test ./...:'
-  cat "$tmpfile"
-  exit 1
+  echo -n 'testing...'
+  go test ./... >"$tmpfile" 2>&1
+  result="$?"
+  echo -en "\r\e[K"
+  if test "$result" -ne 0; then
+    echo 'Error: tests failed, go test ./...:'
+    cat "$tmpfile"
+    exit 1
+  fi
 fi
 
 echo -n 'hashing...'
