precommit: track effdumptest's hash

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -59,4 +59,15 @@ if test "$result" -ne 0; then
   exit 1
 fi
 
+echo -n 'hashing...'
+wanthash=$(cat internal/effdumptest/hash)
+gothash=$(go run github.com/ypsu/effdump/internal/effdumptest hash)
+echo -en "\r\e[K"
+if test "$gothash" != "$wanthash"; then
+  echo "Error got hash $gothash, want $wanthash."
+  echo "$gothash" >internal/effdumptest/hash
+  echo "Expectation auto-updated, rerun git commit."
+  exit 1
+fi
+
 rm "$tmpfile"
